branches:
  only:
  - master
language: python
python:
  - "3.6"
install:
  - pip3 install -r scripts/requirements.txt
script:
  - make
after_success:
  - ./push.sh
env:
  global:
    secure: sibC0I5r3ocHajVA1YWleB6PypDHsN+LR6/VAynfBrlibnanqRU0xM6o7/ILPzpDfzMwGKD3+v9RLSsjMTFBwal9oGJ0AeC20HG4Ya2xcDRna70G7k75xpCfg+3HLYgqqe8QzQHwUwOCpP2wmWhfqybFOACl0Acd2EtiGsrmKNz/c0kdxOo3OqobdNT/2wbOGqk5nKbEdUjFmYrFZoyI+XPs29z3O8a7Vv1atppjvb8vWvb5oUilbTh9thfgRaaDQHokvgPxUbvcNuP99+Oi0IFJP65aUJZkQzpBjpQIf+a8uqW2/Qce5Ry/KmWahaIWsLE5YQCnf1etn5RdZIPKJSljx3/HZGFpOMYz1Bz4+fwK+W+xhZG28Lm3fEx4/aAEPdVo8qlGTrFdpGuk1jlNvotbP/uaflTb4jdRGewvaMycBxV1xd4xzdBQMicZXylWQpDODddsuvOOCp+i5IdLf+rs2PThNckiEd3E916UZhfM4G1rv5SFl7+94avQF31Ms7GE2VzfSWao8PTKQ8zcO8iWQ52aH0nW2FbEj8RwoaWLOfndKN0SPWojogB0FJkaVMS5pbCmMbR/rv5DhEp7oLydH2oPRMJ8WmsUyAsayl7vhkAggXgAMQ6GCw7aviFD4fjpIViR5UUF1QE60GPrOqKnTlQka5wnTE+dSAOatOg=
