# 建构（生成网页和csv）并部署到 gh-pages 分支

name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
    - name: 建构
      run: |
        make
    - name: 部署
      run: |
        ./push.sh
